### ISSUE TITLE
Updated snippet descriptions

### ISSUE THREAD

**Issue by alexgriffis** [TimonVS/vscode-react-standard#4]
If you have any interest in this I can PR: The snippets all have decent descriptions but especially in the case of the lifecycle methods the descriptions don't indicate the name of the method, just its behavior. I've added the method names to my descriptions so the first thing I see is confirmation that I'm selecting the correct snippet.

Example:
"cwup" => "Invoked immediately before rendering when new props or state are being received."
becomes
"cwup" =>  "componentWillUpdate: Invoked immediately before rendering when new props or state are being received."

It may seem verbose but having the name there give a bit of extra confidence, especially when learning the snippets.

**Comment by TimonVS** [comment]
Hi @alexgriffis, great suggestion! It might be better to submit a PR to https://github.com/xabikos/vscode-react. This project is a fork which uses JavaScript Standard style.

**Comment by alexgriffis** [comment]
Thanks, will do! I wasn't sure if this fork was still tracking that extension 👍
